name: Go CI

# Events
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Official predefined action. 

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          # Fix Go version for consistency
          go-version: '1.25'

      - name: Run tests
        run: go test ./...

  build-and-push:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Official predefined action. 

      - name: DockerHub Login
        # Password from stdin prevents token from being accessible in shell history.
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build image
        run: docker build -t dfbello/go-health-api:latest -t dfbello/go-health-api:${{ github.sha }} .

      - name: Push to DockerHub
        run: docker push --all-tags dfbello/go-health-api

  deploy:
    needs: build-and-push

    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          printf '%s' "${{ secrets.EC2_SSH_KEY }}" > ssh-key.pem
          chmod 400 ssh-key.pem

      - name: SSH into the EC2 instance, Pull and run docker image
        run: |
          ssh -i ssh-key.pem ubuntu@${{ secrets.EC2_IP }} <<'EOF'
          set -e
          sudo docker pull dfbello/go-health-api:latest 
          sudo docker stop go-health-api-container || true
          sudo docker rm go-health-api-container || true
          sudo docker run -d \
              --name go-health-api-container \
              -p 80:8080 \
              dfbello/go-health-api:latest
          EOF

      - name: Clean up
        run: rm ssh-key.pem 
